# Generated by Django 6.0.4 on 2026-04-09 07:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级列表',
            },
        ),
        migrations.CreateModel(
            name='SessionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateField(verbose_name='开始日期')),
                ('session_end', models.DateField(verbose_name='结束日期')),
            ],
            options={
                'verbose_name': '训练期',
                'verbose_name_plural': '训练期列表',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='赛事名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '赛事',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('1', '管理员'), ('2', '教练'), ('3', '学员')], default='1', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='coach_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教练',
                'verbose_name_plural': '教练列表',
            },
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.classlevel', verbose_name='所属班级')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weiqi_app.coach', verbose_name='负责教练')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程列表',
            },
        ),
        migrations.CreateModel(
            name='FeedbackCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='反馈内容')),
                ('feedback_reply', models.TextField(blank=True, null=True, verbose_name='回复')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.coach', verbose_name='教练')),
            ],
            options={
                'verbose_name': '教练反馈',
            },
        ),
        migrations.CreateModel(
            name='LeaveReportCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.CharField(max_length=60, verbose_name='请假日期')),
                ('leave_message', models.TextField(verbose_name='请假原因')),
                ('leave_status', models.IntegerField(choices=[(0, '待审核'), (1, '已批准'), (-1, '已拒绝')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.coach', verbose_name='教练')),
            ],
            options={
                'verbose_name': '教练请假',
            },
        ),
        migrations.CreateModel(
            name='NotificationCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='通知内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.coach', verbose_name='教练')),
            ],
            options={
                'verbose_name': '教练通知',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='上课日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.coursesubject', verbose_name='课程')),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.sessionyear', verbose_name='训练期')),
            ],
            options={
                'verbose_name': '考勤课次',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('其他', '其他')], default='男', max_length=10, verbose_name='性别')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='student_profiles/')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('current_rank', models.CharField(choices=[('未定级', '未定级'), ('30K', '30K'), ('25K', '25K'), ('20K', '20K'), ('15K', '15K'), ('10K', '10K'), ('5K', '5K'), ('1K', '1K'), ('1D', '1段'), ('2D', '2段'), ('3D', '3段'), ('4D', '4段'), ('5D', '5段')], default='未定级', max_length=10, verbose_name='当前段位')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weiqi_app.classlevel', verbose_name='班级')),
                ('session_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weiqi_app.sessionyear', verbose_name='训练期')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员列表',
            },
        ),
        migrations.CreateModel(
            name='RankPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_rank', models.CharField(max_length=10, verbose_name='晋级前')),
                ('to_rank', models.CharField(max_length=10, verbose_name='晋级后')),
                ('promotion_date', models.DateField(verbose_name='晋级日期')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '段位晋级',
            },
        ),
        migrations.CreateModel(
            name='NotificationStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='通知内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '学员通知',
            },
        ),
        migrations.CreateModel(
            name='LeaveReportStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.CharField(max_length=60, verbose_name='请假日期')),
                ('leave_message', models.TextField(verbose_name='请假原因')),
                ('leave_status', models.IntegerField(choices=[(0, '待审核'), (1, '已批准'), (-1, '已拒绝')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '学员请假',
            },
        ),
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(verbose_name='对局日期')),
                ('opponent', models.CharField(blank=True, max_length=100, verbose_name='对手')),
                ('sgf_file', models.FileField(blank=True, null=True, upload_to='game_records/', verbose_name='棋谱(.sgf)')),
                ('note', models.TextField(blank=True, verbose_name='复盘笔记')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weiqi_app.coach', verbose_name='指导教练')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '棋谱记录',
            },
        ),
        migrations.CreateModel(
            name='FeedbackStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='反馈内容')),
                ('feedback_reply', models.TextField(blank=True, null=True, verbose_name='回复')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '学员反馈',
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_score', models.FloatField(default=0, verbose_name='平时分')),
                ('exam_score', models.FloatField(default=0, verbose_name='考核分')),
                ('new_rank', models.CharField(blank=True, max_length=10, null=True, verbose_name='晋升段位')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.student', verbose_name='学员')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.coursesubject', verbose_name='课程')),
            ],
            options={
                'verbose_name': '成绩记录',
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='是否出勤')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.attendance', verbose_name='课次')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '考勤明细',
                'unique_together': {('student', 'attendance')},
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(blank=True, null=True, verbose_name='名次')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.student', verbose_name='学员')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_app.tournament', verbose_name='赛事')),
            ],
            options={
                'verbose_name': '参赛记录',
                'unique_together': {('tournament', 'student')},
            },
        ),
    ]
